---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: all
  roles:
    - nfs    # NFS PV Support
    - iscsi  # Longhorn PV Support
    - containerd
  tags:
    - supporting

- hosts: all
  roles:
    - kubernetes
  tags:
    - kubernetes
